### ISSUE TITLE
[ISSUE] URL column type  _ error 403 not displayed in error popup

### ISSUE THREAD

**Issue by mmebsout** [SITools2/SITools2-core#90] opened 2017-11-28 13:40 UTC
Sitools Version : 3.0-beta1 (PSUP instance)
Using Firefox 57.0 (64 bits)

Have a Dataset with a column set to URL to download a different file for each row. 
(example : Dataset OMEGA data Cubes) 
When clicking on the download icon,
If the download is not authorized for the url (or I guess any other error than not found) : the popup of error is empty.

![popup_vide](https://user-images.githubusercontent.com/7287245/33322544-f78a0850-d449-11e7-81fc-c21e92f899e1.png)

**Comment by hubertnouhen** [comment] 2017-12-21 10:06
Hello, Sitools is supposed to request the headers of the resource (HEAD method) and then if available, sitools gets it (GET method). Furthermore, as we can see on the screenshot, the request method is "OPTIONS". Do you know why ?

**Comment by hubertnouhen** [comment] 2017-12-21 10:10
Also, please, check the presence of the following key/value definitions in the "gui.properties" files of your sitools instance :

/client-public-3.0/res/i18n/fr/gui.properties [FR]
label.403=Interdit
label.404=Introuvable
label.fileNotFound=Le fichier demandé est introuvable
label.fileForbidden=Vous n'avez pas les droits nécessaires pour accéder à ce fichier

/client-public-3.0/res/i18n/en/gui.properties [EN]
label.403=Forbidden
label.404=Not found
label.fileNotFound=File not found
label.fileForbidden=You do not have permission to access this file

**Comment by hubertnouhen** [comment] 2017-12-22 11:13
Fixed in v3.1.2

**Closed by hubertnouhen** 2017-12-22 11:13 UTC

**Comment by mmebsout** [comment] 2017-12-22 14:33
Hello, sorry about the delayed answer, I was away from work.
I do have the internationalization keys well set in the gui.properties files.
I don't know why the requests method is OPTION, do you still need me to check it out ? looks like you figured out the fix since then.

**Comment by hubertnouhen** [comment] 2017-12-22 14:47
Hello, I could not reproduce the bug you describe. I fixed maybe something else. If you can reproduce this issue and tell me how to do, i'll be able to figure out what's wrong.

**Comment by mmebsout** [comment] 2017-12-22 15:20
To reproduce this bug:
- go to http://psup-dev.ias.u-psud.fr/sitools/client-user/index.html?project=PLISonMars
- click on "OMEGA data > data" 
- click on search
- in the result table click a cell of the ".sav" column

I cannot guarantee for how long this instance will stay as-is. This url is for a test instance.
