### ISSUE TITLE
Failure of download - from 2nd download

### ISSUE THREAD

**Issue by guanjiwang2016** [SITools2/SITools2-core#61] opened 2016-03-24 08:55 UTC
Bonjour,
    I met a problem when I download the files in page client-user.
    The scenario:  
     1st, in code java, add the path value to access the data storage in OrderResource.java
    2nd, in client-admin, in Dataset services, add 'SERVER Service' to the target dataset
     3rd, in client-user, open the dataset and download the data chosen in the result window, it works. 
            And in client-admin, in  '**Orders**',  I see the status is  '**done**' .
     4th, do another search or refresh the result window and download the data again as the 3rd process, **no response and no download.** in '**Orders**', the new order is created but its status is '**active**' not '**done**'

Thank you for your time. 
Best regards,
guanji

**Comment by guanjiwang2016** [comment] 2016-04-14 09:38
Hello,
    here is the link of my project : http://idoc-solar-portal.ias.u-psud.fr/
the senario:
    1. Click 'Dataset Explorer' module and extend the child tree nodes of 'SDO'
    2. Click on the tree node 'HMI' and choose any series_name, ex hmi.sharp_720s_nrt, then click Search

![selection_121](https://cloud.githubusercontent.com/assets/16957363/14523689/e9c4649a-022c-11e6-93d4-38f10b937b29.png)

    3. Choose any line of data, then click download -> Download tar
    4. Download fails from 2nd download unless I refresh the web page

Thank you for your help.
Regards,
Guanji

**Comment by malapert** [comment] 2016-04-14 13:26
Hi Guanji,

I cannot reproduce your scanario : recnum is empty and I cannot download any file. It would seem there is a problem in the plugin (donwload tar) implementation. Could you tell me if the "download tar" plugin is your or this one delivered with SITools2 ? If it the plugin is your, I am not sure we can do something for you.

Regards

**Comment by guanjiwang2016** [comment] 2016-04-15 15:07
Hi,
   Please try again the scenario. It works now. You can download any line you want.
   I restarted the server.
   I didn't develop the plugin but change the path value. It seems we can not do the 2nd download unless we refresh it.
  Thanks.

Regards,
guanji

**Comment by guanjiwang2016** [comment] 2016-05-12 15:37
Hello,
   We have changed our site from http://idoc-solar-portal.ias.u-psud.fr/ to http://idoc-solar-portal-test.ias.u-psud.fr/
   Thank you.

regards,
guanji

**Comment by malapert** [comment] 2016-08-31 14:16
Hello,

Could you give me please all keywords in the "Parameters Mapping" menu of your plugin ?

Thanks

**Comment by guanjiwang2016** [comment] 2016-08-31 14:57
Hello,
   Here is the captured picture below.
![image](https://cloud.githubusercontent.com/assets/16957363/18133663/60b7f3ea-6f93-11e6-87f8-b124dab4fe13.png)

   And I created some plugin based on OrderResourceModel and all plugin allow to download only at 1st time.
   Thanks,

regards,
guanji

**Comment by malapert** [comment] 2016-09-28 15:35
Precision from Guanji : It works when the administrator configures the plugin with the option  "display in new tab" but it does not work when the administrator uses the option "display in desktop"

**Comment by guanjiwang2016** [comment] 2017-05-05 14:10
Hello, 
    The same error is always there. 
    Scenario: 
    1.  Open [idoc_medoc_test interface](http://idoc-medoc-test.ias.u-psud.fr) , close the HELP module window.
    2.  Select dataset graphic tree in the **Explore data** menu
    3. Extend the SOHO tree node, open CDS dataset table on the left.
    4. In the result window, select any record then click download button in the menu bar.

The 1st download works but 2nd 3rd .. don't.
The 'display in desktop' option doesn't work well.

Thank you,
Regards,
guanji

**Comment by MedocIAS** [comment] 2017-05-17 08:25
Hi,
We would like to deploy in production soon.
May we have a status on that one please ? 

Best regards
Pablo

**Comment by bfiorito** [comment] 2017-05-23 12:57
Fixed in commit 30ed67bcc3ac8bc693bce16a078997437d156ab9

**Closed by bfiorito** 2017-05-23 12:57 UTC
Labels: bug
